version: "3.7"

services:
  client-ui:
    container_name: annio-client-ui
    image: annio-client-ui:latest
    build:
      context: ../../client-ui
      args:
        - PORT=$WEB_CLIENT_UI_PORT
        - DEBUG_PORT=$WEB_CLIENT_UI_DEBUG_PORT
        - API_URL=$BACKEND_SERVICE_URL
    tty: true
    stdin_open: true
    ports:
      - $WEB_CLIENT_UI_PORT:$WEB_CLIENT_UI_PORT
      - $WEB_CLIENT_UI_DEBUG_PORT:9229
    volumes:
      - ../../client-ui:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - annio-net
    depends_on:
      - api-services
  api-services:
    container_name: annio-api-services
    image: annio-api-services:latest
    build:
      context: ../../api-services
      args:
        - PORT=$API_PORT
        - DEBUG_PORT=$DEBUG_PORT
        - API_PREFIX=$API_PREFIX
        - SERVICE_ORDER_HOST=$SERVICE_ORDER_HOST
        - SERVICE_ORDER_PORT=$SERVICE_ORDER_PORT
        - SERVICE_PAYMENT_HOST=$SERVICE_PAYMENT_HOST
        - SERVICE_PAYMENT_PORT=$SERVICE_PAYMENT_PORT
    tty: true
    stdin_open: true
    ports:
      - $API_PORT:$API_PORT
      - $DEBUG_PORT:9229
    volumes:
      - ../../client-ui:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - annio-net
    depends_on:
      - order-service
      - payment-service
  order-service:
    container_name: annio-order-service
    image: annio-order-service:latest
    build:
      context: ../../order-service
      args:
        - PORT=$SERVICE_ORDER_PORT
        - DEBUG_PORT=$SERVICE_ORDER_DEBUG_PORT
        - DB_HOST=$DB_HOST
        - DB_PORT=$DB_PORT
        - DB_USERNAME=$DB_USERNAME
        - DB_PASSWORD=$DB_PASSWORD
        - DB_NAME=$DB_NAME
        - SERVICE_PAYMENT_HOST=$SERVICE_PAYMENT_HOST
        - SERVICE_PAYMENT_PORT=$SERVICE_PAYMENT_PORT
        - DELIVERY_SECOND_DELAY=$DELIVERY_SECOND_DELAY
    tty: true
    stdin_open: true
    ports:
      - $SERVICE_ORDER_PORT:$SERVICE_ORDER_PORT
      - $SERVICE_ORDER_DEBUG_PORT:9229
    volumes:
      - ../../orders-service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - annio-net
    depends_on:
      - db
  payment-service:
    container_name: annio-payment-service
    image: annio-payment-service:latest
    build:
      context: ../../payment-service
      args:
        - PORT=$SERVICE_PAYMENT_PORT
        - DEBUG_PORT=$SERVICE_PAYMENT_DEBUG_PORT
        - DB_HOST=$DB_HOST
        - DB_PORT=$DB_PORT
        - DB_NAME=$DB_NAME
        - DB_USERNAME=$DB_USERNAME
        - DB_PASSWORD=$DB_PASSWORD
        - SERVICE_ORDER_HOST=$SERVICE_ORDER_HOST
        - SERVICE_ORDER_PORT=$SERVICE_ORDER_PORT
    tty: true
    stdin_open: true
    ports:
      - $SERVICE_PAYMENT_PORT:$SERVICE_PAYMENT_PORT
      - $SERVICE_PAYMENT_DEBUG_PORT:9229
    volumes:
      - ../../backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - annio-net
    depends_on:
      - db
  db:
    container_name: annio-mysql
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - $DB_PORT_EXTERNAL:$DB_PORT
    networks:
      - annio-net

volumes:
  db-data:

networks:
  annio-net:
